version: '3'

services:


###################################
#  set up frontend container
###################################

  frontend:
    build: ./frontend
    ports:
      - 4200:4200
    expose:
      - 4200
    command: node app.js
    # volumes:
    #   - ./frontend:/app


